### PR TITLE
Update to ubuntu 20.10 - newer version of novnc

### PR DESCRIPTION
**Pull request by rompic**
novnc in ubuntu 20.10 is way newer and has some nice features like zooming and fullscreen mode in browsers that support it.

### CODE REVIEW

**Review by theonemule — APPROVED** [review]

**Comment by oudmeister** [comment]
As a complete noob, I'm trying to get this to work on my PC (I'm hoping to modify this approach towards other linux based emulators I found). Unfortunately, I get stuck.
I am running Docker Desktop on windows, but what I understand from Docker this should not be an issue.
To minimize the variables and pinpoint the problem I downloaded the very same game (keen). I seem to be able to create the container fine.
I get some messages in red:
"`debconf: delaying package configuration, since apt-utils is not installed`"
later on I get
```
Warning: password truncated to the length of 8.
Generating a RSA private key
.................................+++++
...........................................................+++++
writing new private key to '/root/novnc.pem'
-----
```
, but it ends with a reassuring:
```
Successfully built e2b4b2a0f7b5
Successfully tagged mydosbox:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

using `docker run -p 6080:6080 dosbox`
leads to:

```
Unable to find image 'dosbox:latest' locally
docker: Error response from daemon: pull access denied for dosbox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
I never built dosbox, so it made sense to me to change the command to `docker run -p 6080:6080 dosbox`
which seems to work considering the output:

```
xauth:  file /root/.Xauthority does not exist

New 'X' desktop is 62b5b2a8288d:1

Creating default startup script /root/.vnc/xstartup
Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/62b5b2a8288d:1.log

WebSocket server settings:
  - Listen on :80
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
```
However, I cant open a page on "http://localhost:6080/vnc.html"

Looking into the dockerfile I wondered if I should use another port. I therefore stopped the running container  and tried `docker run -p 6080:5901 mydosbox`

When I try to open page "http://localhost:6080/vnc.html" I get an empty page with RFB protocol response?:
`RFB 003.008`
I use Firefox on Windows10.

Clearly I'm missing something obvious? Could you nudge me in the right direction?

**Comment by rompic** [comment]
@oudmeister looks like this part of the readme is outdated as well. the dockerfile exposes port 80 
so you should do 
docker run -p 6080:80 mydosbox
instead

all your other changes are not necessary afaik.

**Comment by rompic** [comment]
@oudmeister i reread your comment and created https://github.com/theonemule/dos-game/pull/4 . maybe that clarifies things / helps.

**Comment by oudmeister** [comment]
It works now. Thanks a lot! I also found that if you use
localhost:6080/vnc_auto.html?password=password1 you can start without the
need to press connect (the link is less secure ofc).
Is it correct that the connection is unencrypted? I sort of expected it to
get encrypted with the certificate and all?

Best regards,
Oudmeister

**Comment by theonemule** [comment]
The certificate was required for something... I don't remember exactly, but it isn't used by the web server. If you want that, you'd need something like NGINX or HAProxy to a reverse proxy.

**Comment by oudmeister** [comment]
Hi Blaize,

I was trying to add sound by combining your project with this one to get
sound:
vexingcodes/dwarf-fortress-docker: Easily run Dwarf Fortress in an
unprivileged Docker contianer. (github.com)
<https://github.com/vexingcodes/dwarf-fortress-docker>
I think I got pretty far, but I seem to be missing something. I use the
following three files from the mentioned project:
- client.conf
<https://github.com/vexingcodes/dwarf-fortress-docker/blob/main/client.conf>
- default.pa
<https://github.com/vexingcodes/dwarf-fortress-docker/blob/main/default.pa>
- webaudio.js
<https://github.com/vexingcodes/dwarf-fortress-docker/blob/main/webaudio.js>

and I made the following Dockerfile to try it with commander Keen:

FROM debian:buster
ENV USER=root
ENV PASSWORD=password1
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
COPY keen /dos/keen

RUN apt-get update && \
    apt-get install -y \
    gstreamer1.0-plugins-good \
    gstreamer1.0-pulseaudio \
    gstreamer1.0-tools \
    libglu1-mesa \
    libgtk2.0-0 \
    libncursesw5 \
    libopenal1 \
    libsdl-image1.2 \
    libsdl-ttf2.0-0 \
    libsdl1.2debian \
    libsndfile1 \
    pulseaudio \
    supervisor \
    ucspi-tcp \
    x11vnc \
    xvfb \
    tightvncserver \
    ratpoison \
    dosbox \
    novnc \
    websockify && \
    rm -rf /var/lib/apt/lists/*

COPY default.pa client.conf /etc/pulse/
COPY webaudio.js /usr/share/novnc/core/

RUN ln -s /usr/share/novnc/vnc_lite.html /usr/share/novnc/index.html && \
    sed -i 's/display:flex/display:none/'
/usr/share/novnc/app/styles/lite.css && \
    sed -i "/import RFB/a \
    import WebAudio from './core/webaudio.js'" \
    /usr/share/novnc/vnc_lite.html && \
    sed -i "/function connected(e)/a \
    var wa = new WebAudio('ws://localhost:8081/websockify'); \
    document.getElementsByTagName('canvas')[0].addEventListener('keydown',
e => { wa.start(); });" \
    /usr/share/novnc/vnc_lite.html


RUN mkdir ~/.vnc/ && \
mkdir ~/.dosbox && \
echo $PASSWORD | vncpasswd -f > ~/.vnc/passwd && \
chmod 0600 ~/.vnc/passwd && \
echo "set border 0" > ~/.ratpoisonrc  && \
echo "exec dosbox -conf ~/.dosbox/dosbox.conf -fullscreen -c 'MOUNT C:
/dos' -c 'C:' -c 'cd keen' -c 'keen1'">> ~/.ratpoisonrc && \
export DOSCONF=$(dosbox -printconf) && \
cp $DOSCONF ~/.dosbox/dosbox.conf && \
sed -i 's/usescancodes=true/usescancodes=false/' ~/.dosbox/dosbox.conf

EXPOSE 8080 8081

CMD vncserver && \
    websockify -D --web=/usr/share/novnc/ 8080 localhost:5901 && \
    /usr/bin/pulseaudio --disallow-module-loading -vvvv --disallow-exit
--exit-idle-time=-1 && \
    tcpserver localhost 5902 gst-launch-1.0 -q pulsesrc
server=/tmp/pulseaudio.socket ! audio/x-raw, channels=2,     rate=24000 !
cutter ! opusenc ! webmmux ! fdsink fd=1 && \
    websockify 8081 localhost:5902 && \
    /bin/bash -c 'sleep 10 && /home/df/df_linux/df'

I can build it successfully..
docker build -t keenbox:latest .

I can also run it...
docker run -ti -p 8080:8080 -p 8081:8081 keenbox:latest

I can play the game opening
localhost:8080/vnc_auto.html?password=password1
Unfortunately I get no sound (I am assuming this dos version of keen does
have sound?). Would you maybe have an idea what I'm missing here?

Best regards,
Oudmeister

**Pull request merged**
